### ISSUE TITLE
Env keyword argument error: computeServers

### ISSUE THREAD

**Issue by l85m** [Gurobi/instantcloud-python#1]
Getting keyword argument error on Env:

```
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from instantcloud import InstantCloudClient
>>> from gurobipy import *
>>> machinename = <redacted>
>>> userpassword = <redacted>
>>> env = Env("gurobi.log", computeServers=machinename, port=GRB.DEFAULT_CS_PORT, password=userpassword)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env.pxi", line 20, in gurobipy.Env.__init__ (../../src/python/gurobipy.c:5391)
TypeError: __init__() got an unexpected keyword argument 'computeServers'

```

Tried on both versions 6.0.5 and 6.5.0. Python is default MacOS python.

**Comment by gglockner** [comment]
This isn't a bug in instantcloud-python, but it does appear to be a bug in the documentation. The syntax should be:

    env = Env.ClientEnv(("gurobi.log", computeServers=machinename, port=GRB.DEFAULT_CS_PORT, password=userpassword)
